server:
  port: 80

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.174.182:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.chen.blog: info

  file:
    name: log/blog-pro.log