spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30000
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true


comment.avatar: /static/images/avatar.jpg
