server:
  port: 8088

spring:
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
# 日志配置
logging:
  config: classpath:logback-prod.xml
  level:
    root: warn
    com.chen.blog: debug
    org.springframework: warn

#  file:
#    name: log/blog-pro.log
upload:
  serverUrl: http://localhost:8088
  picturePath: file:D:\blog\PicturePath
#  picturePath: file:/opt/picturePath
